### ISSUE TITLE
Feature request:  limit the number of dots visible

### ISSUE THREAD

**Issue by i300220** [kenwheeler/slick#2130] opened 2016-02-17 20:16 UTC
This is an example of how the dots display when there's a lot of images in the slideshow.
![slideshow_dot_navigation_2016-02-18_at_04 43 01](https://cloud.githubusercontent.com/assets/15702355/13123275/7333771e-d589-11e5-9ea4-e1f6056f6b4d.jpg)

**Comment by leggomuhgreggo** [comment] 2016-02-17 22:11
Hey @i300220 please check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)--in general it's pretty critical for debugging to have a reduced test case in a fiddle or codepen so we require it for issues--although in this case I can understand how its pretty well illustrated by the screenshot. 

Im gonna go ahead and close this because I wouldn't really call this a bug--that said if you have a reasonable idea as to some default way to handle this case I'd be curious to hear it!

I thought I remembered someone else with something similar and found [this issue](https://github.com/kenwheeler/slick/issues/1799). Often times if you search past issues you can find something relevant. Anyway you should be able to customize a solution pretty easily or just turn dots off.

Hope that helps!

**Closed by leggomuhgreggo** 2016-02-17 22:11 UTC

**Comment by i300220** [comment] 2016-02-17 22:53
Awesome.  Thanks for the kind help!

**Comment by Luc45** [comment] 2017-10-24 14:24
I would just like to point out that I have this issue too. I have sliders with over 60 images with lazy-load on, and I get like 3 rows of dots. It would be nice to have an arrow to loop through them if they have more than 100% of the width of the slider.

Fiddle:
https://jsfiddle.net/qg7g9n8p/

_I couldn't make dots look beautiful, but it reproduces the behaviour neverthless :)_

**Comment by vonhutrong** [comment] 2018-02-09 10:01
I have try above css but it doesn't work properly for my case. So I create this code, I hope that it's helpful :)

[code](https://github.com/vonhutrong/note/blob/master/slick%20slide%20-%20limit%20number%20of%20dots.js)

p/s: I cannot use insert code feature of comment blog to add highlight code

**Comment by i300220** [comment] 2018-02-12 02:05
@vonhutrong added a couple of fixes to your code.  it wouldn't work as is.  using it right now.  thanks so much for that wonderful feature!

**Comment by vonhutrong** [comment] 2018-02-12 05:22
@i300220 I have add more comment, I hope that it is clear enough for other one who want to use it :).

**Comment by gjulivan** [comment] 2018-03-09 09:25
is this issue have work around?

**Comment by pscdodd** [comment] 2018-03-09 09:43
CSS selectors :nth-child(n) ?

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Grand Julivan<mailto:notifications@github.com>
Gesendet: Freitag, 9. März 2018 10:25
An: kenwheeler/slick<mailto:slick@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: Re: [kenwheeler/slick] Feature request: limit the number of dots visible (#2130)


is this issue have work around?

**Comment by swarad07** [comment] 2019-01-08 13:53
I recently developed something like this, https://codepen.io/swarad07/pen/xmzQKm.

I have restricted the dots to 5 (but can be any number), and scroll them similar to instagram.

**Comment by azarGIT171987** [comment] 2019-01-30 13:34
Any Update Or Release On This ?
I need Dots Based On Number Of Slides Per Page
And Any Way We Can Have Diff SlideToscroll Value For Dots And Navigation?
