### ISSUE TITLE
Filter/Unfilter and breakpoints not functioning properly

### ISSUE THREAD

**Issue by jasonsan3** [kenwheeler/slick#1567] opened 2015-07-23 20:12 UTC
Here is a full demo of the issue: https://jsfiddle.net/jasonsan3/ocfL0q2j/2/

Slick works well before the breakpoint. Filtering and Unfiltering are triggered predictably. At breakpoint, the filtering/unfiltering stops working correctly. It seems that there is a failure to adjust the 3d transform settings, but I can't quite figure out what is happening.

Also, in the jsfiddle, I have used a mobileFirst setting. However, if I take that out, the issue persists, just in the opposite direction. That is, if the break is met from moving large to small, then it is the same error. It seems that something is set when the slick is first initialized that fails after a breakpoint.

Thank you.

**Comment by CAYdenberg** [comment] 2015-07-23 22:12
I have a similar issue. Demo: http://codepen.io/CAYdenberg/pen/ZGqbzw

It looks like this was referenced in #366 and a partial solution was submitted by @smk1 but it seems to have forgotten.

**Comment by ramon-villain** [comment] 2015-07-24 01:39
Hi guys, check this https://github.com/kenwheeler/slick/pull/1569 this fixed for me.

**Comment by jasonsan3** [comment] 2015-07-24 14:01
Thanks @ramon-villain this fix worked like a charm. Startling to see something work on my first try. Much appreciated! Just in case someone googles this later...

Edit slick.js (version 1.5.6) lines 627 and 634. Just delete those lines, or comment them out. The lines are as follows.
Line 627:
```
_.refresh(initial);
```
and Line 634:
```
_.unslick(targetBreakpoint);
```
Thanks again to @ramon-villain in reference to fix #1569 as described above.

**Comment by simeydotme** [comment] 2015-07-24 14:03
I think the issue is not closed.
lopping out code for your specific use-case is not the same as fixing an issue :P
there's a million options for slick. I'll leave this open until it has been investigated properly.

**Comment by jasonsan3** [comment] 2015-07-24 14:14
Great, thank you @simeydotme.

**Comment by CAYdenberg** [comment] 2015-07-24 17:27
Thank you @ramon-villain! In my hands, this PR fixes #366 in my project and in the codepen: http://codepen.io/CAYdenberg/pen/NqOpEG. 

The ONLY issue I see is if: you select a filter, resize outside of the breakpoints (ie, so that responsive mode is not being used), and then select a different filter. In that case, it doesn't behave properly.

Still, this is a relatively minor use-case, so I'll be using the updated code on my project.

**Comment by aberonni** [comment] 2015-08-31 15:54
+1 on this issue - I'm having the same problem. 

The suggested fix does seem to solve the problem - but I also encounter the issues reported by @CAYdenberg .

**Comment by valentinvoilean** [comment] 2015-09-15 13:45
+1

**Comment by TomOne** [comment] 2015-10-07 12:57
I have the same issue.

**Comment by elgrafico** [comment] 2015-10-16 14:24
Afaics the issue originates in the not-so-well-written refresh function.

```Slick.prototype.refresh = function( initializing )``` expects `initializing` to be boolean and does not validate that assumption.

If you like to hack that particular one away, change https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1540 
```if( !initializing ) {``` to 
```if (typeof initializing !== "boolean" || !initializing ) {```

**Comment by leggomuhgreggo** [comment] 2016-04-27 23:21
Hey I know this issue was created a while ago, but if you’re still interested can you recreate in a [fiddle with the master](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
)? Thanks and apologies for the dormancy.

Closing pending updated fiddle

**Closed by leggomuhgreggo** 2016-04-27 23:21 UTC

**Comment by SashaSansay** [comment] 2017-07-27 10:14
The same issue.

JSFidle: http://jsfiddle.net/kq17qknt/

There we can see that slick permanently removes some items from dom and ufliter method not working properly.
