### ISSUE TITLE
Flexible width w/ responsive, dynamic slidesToShow.

### ISSUE THREAD

**Issue by louiswalch** [kenwheeler/slick#2245] opened 2016-04-13 19:51 UTC
Is it possible to define a desired width for each slide, and have the slidesToShow calculate automatically without defining a bunch of breakpoints? 

For example I want my slidesToShow to equal Math.floor( window_width / 250)

**Comment by leggomuhgreggo** [comment] 2016-04-13 23:32
I think you're looking for `variableWidth: true`. Hope that helps!

Closing: Support Req, not a bug

**Closed by leggomuhgreggo** 2016-04-13 23:32 UTC
