### ISSUE TITLE
change direction of vertical slider

### ISSUE THREAD

**Issue by hazeways** [kenwheeler/slick#2075] opened 2016-01-27 21:56 UTC
I guess this is a simple task, however I cannot manage to find a solution. I want the slider that I choose to have vertical to rotate down instead of up. I have tried to change the rtl and direction values without any success. Can anybody help?

**Comment by simeydotme** [comment] 2016-01-28 06:29
Duplicate of #818

**Closed by simeydotme** 2016-01-28 06:29 UTC
Labels: Invalid: Duplicate
