### ISSUE TITLE
Page scrolls

### ISSUE THREAD

**Issue by grammka** [kenwheeler/slick#1700] opened 2015-09-07 00:26 UTC
When I press arrows / dots (in example too) slide changes and after animation finished page scrolled top for no reason. How to prevent this?
PS I tried to set containers height to prevent block from resizing via vertical..

**Comment by kenwheeler** [comment] 2015-09-07 12:38
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown

**Closed by kenwheeler** 2015-09-07 12:38 UTC

**Comment by antokara** [comment] 2015-11-26 09:08
@grammka you are right, this happens only when navigation is triggered from dots.

@kenwheeler, I understand that you need a jsFiddle to find out what is the problem, the thing is, this "bug" also happens in your demos with bullets: https://kenwheeler.github.io/slick/
just go to your "Fade" demo, scroll the page a bit past the example, so that only half the image is visible (it is important) and then simply click any of the navigation dots. You will see that the page is scrolled back up to "show" the whole image...

I believe the problem is located here
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L705
```
                $target.children().trigger('focus');
```

Although this can be useful, it can also create issues in some cases and I would suggest a boolean option enabled by default, which will allow anyone to disable if required.

**Comment by antokara** [comment] 2015-11-26 09:28
Update: it appears to be already fixed here e49755e89789d0e3750e78f83de0d4ff3fbf2721
and it merged in master but it not included in the 1.5.8 tag
and its probably a duplicate issue of #1537 with #1637
