### ISSUE TITLE
New major version to be still expected?

### ISSUE THREAD

**Issue by floriancapelle** [kenwheeler/slick#2428] opened 2016-07-19 15:18 UTC
The major version 2 branch doesn't seem to be developed any further.
I'd like to know whether a version update is to be expected and if you can provide an estimation for a release date.

We're using the plugin in production regularly and we are kind of dependent on fixes. I'd rather not switch to another plugin, as i like this one and it fits our requirements.

Thank you in advance for any information.
Best regards.

**Comment by leggomuhgreggo** [comment] 2016-07-20 16:55
What's your latest thinking on this @kenwheeler ?

**Comment by kenwheeler** [comment] 2016-07-20 21:25
Which fixes are you dependent on in the 2 branch?

**Comment by pradeeptirmal** [comment] 2016-07-22 20:33
The carousel has some key known issues. The carousel has width issues when added in a table>tbody>td,  a accordion and a modal

**Comment by kenwheeler** [comment] 2016-07-22 20:40
Those issues will never be fixed. Unless you add table layout fixed, it autogrows when doing dimension calcs. For modals, you have to fire a resize event.

**Comment by pradeeptirmal** [comment] 2016-07-22 20:42
Ya. I figured out the solution for modal and table. But the issue with accordion still there. Not able to find a solution to that. Struggling to figure out this one. The first image has width zero. Rest are working fine.

Thanks for the quick reply

**Comment by kenwheeler** [comment] 2016-07-22 20:48
when your accordion opens, call a resize event. when its closed it doesn't have any dimensions to calculate off of, so its 0. its not a bug, its just a circumstance of the enviroment in which its being put.

**Closed** 2016-07-25 13:45 UTC

**Comment by giovannipds** [comment] 2017-03-22 20:42
How's this also closed? We're in the 1.6.0 and apparently abandoned... =/

**Comment by leggomuhgreggo** [comment] 2017-03-22 21:40
There's actually have another release on deck, but haven't yet pulled the trigger. I'll see if I can get that going.

As a general SotU, I'll say that all the maintainers are all insanely busy -- a lot changes in 4 years of course and it's hard to keep time allotted for our dear Slick repo, particularly since it's all volunteer. There's also a little operational ambiguity between patching the v1 and going full steam on v2.

I'll try to make some time to sort out some issues this week. Hopefully I or one of the other contributors will get some bandwidth to make some fixes or HAM out v2, but of course, the beauty of open source is that anyone is free to fork the repo and undertake improvements 😉 

Anyway, appreciate the commentary.

**Comment by giovannipds** [comment] 2017-03-23 00:09
I have gotten in touch with @kenwheeler by email, I'll try to help you guys, checking the issues and PRs, if allowed. Thanks.
