### ISSUE TITLE
center mode not working when slides are equal to slidesToShow

### ISSUE THREAD

**Issue by jullermss** [kenwheeler/slick#1302] opened 2015-05-01 17:19 UTC
Hi, I'm using slicker but I have a problem.

I have:

             <div class="thumbnail-gallery-container">
                                
                    <div class="thumbnail ">
                        <img src="../images/one.png" alt="pic_one" />
                    </div>
                    <div class="thumbnail ">
                        <img src="../images/two.png" alt="pic_two" />
                    </div>
                    <div class="thumbnail ">
                        <img src="../images/three.png" alt="pic_three" />
                    </div>        
                </div>

$thumnailContainer.slick({
        slidesToShow: 3,
        slidesToScroll: 1,
        arrows: true,
        infinite: true,
        dots: false,
        centerMode: true,
        focusOnSelect: true,
        variableWidth: true
    });

-----

The problem is that when I have the same number of slides and slidesToShow, the div "slider-track" have an inline style of "transform: translate3d(137px, 0px, 0px);" and that makes that this is not center.

This is how it look
![3slides](https://cloud.githubusercontent.com/assets/4162468/7433955/532332ea-f004-11e4-9c94-29c33ad93ffd.png)

But when I have 4 slides and slidesToShow = 3, it looks fine:
![4slides](https://cloud.githubusercontent.com/assets/4162468/7433999/9543f0a6-f004-11e4-93a2-9974a622bbc3.png)

Is there any way that I can make this 3 slides respect the center mode and not adding the ""transform: translate3d(137px, 0px, 0px)"  when numberOfSlides == slidesToShow ??

Thank you!!

**Comment by eakroko** [comment] 2015-05-20 19:57
I think that's a duplicate of #1059

**Closed** 2015-06-16 13:59 UTC

**Comment by danodm** [comment] 2015-06-17 04:58
For anyone having this issue and looking for a fix, see my comment on issue #1059 for fix with modified code.

**Comment by alexfromapex** [comment] 2016-04-21 20:37
Is there a shim fix? I'd rather not modify my included Slick JS file, as I need it to be delievered on a CDN.

**Comment by leggomuhgreggo** [comment] 2016-04-21 20:47
None that I'm aware of.

**Comment by laurentmor** [comment] 2017-03-31 19:03
Hi! 
I don't think this deserved another ticket so, I opted to comment this one with my issue.
The issue reported by OP appears to occur regardless of the fix proposed in pull-request #2118 

With the following configuration : 
`$('.td-tab-items-ext').slick({

                            mobileFirst: false,
                            dots: false,
                            infinite: false,
                            arrows: false,
                            speed: 300,
                            centerMode:false,
                            centerPadding:30,
                            slidesToShow: numSlides,
                            slidesToScroll: numSlides,
                            responsive: [
                                {
                                    breakpoint: 769,
                                    settings: {
                                        settings: "slick",
                                        centerMode:true,
                                        slidesToShow: 4,
                                        slidesToScroll: 1
                                    }
                                },
                                {
                                    breakpoint: 420,
                                    settings: {
                                        settings: "slick",
                                        centerMode:false,
                                        slidesToShow: 3.5,
                                        slidesToScroll: 1
                                    }
                                }//..` 
I get the following result:

![tablpng](https://cloud.githubusercontent.com/assets/1400110/24565317/bf3e9dfc-1622-11e7-86cf-b6aca2b24df6.png)

I have slick 1.6.0 defined as a dependency in my bower.json file

any clues on how to fix this ?
Thank you!

**Comment by flinch85** [comment] 2019-05-07 09:43
Hello, this problem still stands. Any fix yet? Thank you!

**Comment by NicoleMarieBRFR** [comment] 2020-04-01 13:09
Hi, I fixed this problem with some css !!

.slider {
  width: 80%;
  margin: 100px auto;
}

.slick-slide {
  margin: 10px 20px;
}

.slick-slide img {
  width: 100%;
  transform: scale(0.9);
}

.slick-prev:before,
.slick-next:before {
  color: black;
}
.slick-dotted .slick-center img {
  transform: scale(1.1);

}

@flinch85 @laurentmor

**Comment by AlexNik17** [comment] 2023-12-14 12:16
This is common due to **paddings**. Remove **paddings** from slick-slide and add them for child elements.
