### ISSUE TITLE
Filtering + asNavFor + focusOnSelect =  indices all buggered up?

### ISSUE THREAD

**Issue by Kiloblargh** [kenwheeler/slick#807] opened 2014-11-18 21:54 UTC
I made two synced sliders for a people profile page- you can click or swipe to the thumbnails on top, and the bottom will move to show that person's full info. 
When it's initially showing all the people; it works fine.

After filtering, it's broken. Some of the thumbs will jump the slider to the wrong person, or cycle through all the slides back to the same one, or not work at all. If I inspect the source, I see that there are more than one slide with the same index number, which is probably what's causing that behavior.

The problem may that I have multiple classes assigned- for example, the same person might be classified as both 'faculty' and 'staff.'  My real page is being generated by a Wordpress query where the category names are being inserted into the class attribute of the bio-thumb and bio-info divs. Here's a simplified version:

http://jsfiddle.net/gigablargh/gth8gvLk/28/

I thought to first do "unFilter()" on both sliders before re-filtering them because I thought that might fix the problem; but that doesn't seem to make any difference. Not sure what else to try. Is the filtering known not to work when members are not unique? Or if this is something that should work, what else  am I doing wrong?

**Comment by kenwheeler** [comment] 2015-01-31 20:03
Closing as a dupe of #344

**Closed by kenwheeler** 2015-01-31 20:03 UTC
Labels: Under Investigation
