### ISSUE TITLE
first slide 'pops-in' when using infinite and you get to the end of the loop

### ISSUE THREAD

**Issue by v3nt** [kenwheeler/slick#2180] opened 2016-03-04 18:12 UTC
> short description of the bug / issue, provide more detail below.

Displaying 1 image at a time and want the slideshow to be infinite and be able to see upcoming slides to the right. However when you get to the end of the loop the first slide doesn't appear in time and jumps is. 

The container is 100% wide so 2 or more images can be previewed to the right. If the last side is visible (but not active) you can see a space where slide 1 should be re-appearing.

====================================================================

###### `[  http://dmfkdev.jynk.net/projects/berners-street/  ]`  

```
    jQuery('#project-image-carousel').slick({
      dots: true,
      arrows: true,
      infinite: true,
      speed: 350,
      slidesToShow: this.s_slidesToShow,
      centerMode: false,
      variableWidth: true,
      prevArrow: '<span class="slick-prev icon-play3"></span>',
      nextArrow: '<span class="slick-next icon-play3"></span>',
      appendArrows: '.slider-nav-container',
      appendDots: '.slider-nav',
      useTransform: true,
      responsive: [
      {
        breakpoint:695,
        settings: {
          dots: false,
          arrows:false
        }
      }
    ]
```

====================================================================

#### Steps to reproduce the problem

1. load the page {http://dmfkdev.jynk.net/projects/berners-street/ }
2. swipe or click until you get to the end of the slideshow.
3. You will see the 1st slide jumping in instead of smoothly coming in from the site

====================================================================

#### What is the expected behaviour?

Not be able to notice the loop by seeing the first slide pop in. Or infinite should be infinite.

====================================================================

#### What is observed behaviour?

1st slide pops into view instead of smoothly coming from the side

====================================================================

#### More Details

All browsers
- Which jQuery/Slick version are you using?
Latest
- Did this work before?
Nope. Always been like this.

**Comment by leggomuhgreggo** [comment] 2016-03-08 14:41
Hey @v3nt I think this is a duplicate of #1207 Im gonna close, but if you think it's a unique bug we can look at reopening. Thanks!

**Closed by leggomuhgreggo** 2016-03-08 14:41 UTC

**Comment by v3nt** [comment] 2016-03-08 18:00
thanks leggomuhgreggo - sure is the same... D.
