### ISSUE TITLE
Extra css class when centerMode is enabled

### ISSUE THREAD

**Issue by kiarashi** [kenwheeler/slick#2229] opened 2016-03-31 22:41 UTC
When I enable centerMode and use 4 slides to show:

```
slidesToShow: 4,
centerMode: true,
```
the source code is like this:

```
<div class="slider">
    <ul class="slick-initialized slick-slider">
		<li class="slick-slide">...</li>
        <li class="slick-slide">...</li>
        <li class="slick-slide slick-active">...</li>
		<li class="slick-slide slick-active">...</li>
        <li class="slick-slide slick-current slick-active slick-center">...</li>
        <li class="slick-slide slick-active">...</li>
		<li class="slick-slide slick-active">...</li>
        <li class="slick-slide">...</li>
		<li class="slick-slide">...</li>
    </ul>
</div>
```

Is there a way to add extra classes to `slick-active`, like this

```
<div class="slider">
    <ul class="slick-initialized slick-slider">
		<li class="slick-slide">...</li>
        <li class="slick-slide">...</li>
        <li class="slick-slide slick-active pre-one">...</li>
		<li class="slick-slide slick-active pre-two">...</li>
        <li class="slick-slide slick-current slick-active slick-center">...</li>
        <li class="slick-slide slick-active post-one">...</li>
		<li class="slick-slide slick-active post-two">...</li>
        <li class="slick-slide">...</li>
		<li class="slick-slide">...</li>
    </ul>
</div>
```

**Comment by leggomuhgreggo** [comment] 2016-03-31 23:07
You'll want to check out the beforeChange event. Hope that helps!

Closing: not a bug, support req, no fiddle

**Closed by leggomuhgreggo** 2016-03-31 23:07 UTC

**Comment by kiarashi** [comment] 2016-04-01 08:45
Would it be possible to give an example? I'm a total noob when it comes to js.

I created a fiddle here:
https://jsfiddle.net/ezw9v81x/24/
