### ISSUE TITLE
slidesToScroll > 1 while centerMode = true - bug

### ISSUE THREAD

**Issue by befreestudios** [kenwheeler/slick#917] opened 2015-01-11 22:14 UTC
Is this a bug? If not, could we make it a feature request? ... see also link to fiddle at bottom. Thanks in advance, btw the plugin rocks!

Steps to recreate: (already setup in fiddle)
When centerMode = true, slidesToScroll is only sliding 1 regardless of what is set.  

Expected: if centerMode = true and slidesToScroll = 3, nav items should scroll 3 slides on center.

FIDDLE HERE...
http://jsfiddle.net/befreestudios/hk5uqb5w/

**Comment by befreestudios** [comment] 2015-01-13 03:24
I think #541 is related.

**Comment by kenwheeler** [comment] 2015-01-13 16:46
Closing as a dupe of 659

**Closed by kenwheeler** 2015-01-13 16:46 UTC
