### ISSUE TITLE
Slick filter is not working when using responsive

### ISSUE THREAD

**Issue by tsbilguun7167** [kenwheeler/slick#1701] opened 2015-09-07 05:27 UTC
Hello ken i really like your project and it saved too many hours to work. At last i found a bug that when i define slick with responsive settings. My js code is  
   $('.responsive').slick({
    dots: false,
    infinite: true,
    autoplay: true,
    speed: 300,
    slidesToShow: 9,
    slidesToScroll: 1,
    responsive: [
        {
            breakpoint: 1600,
            settings: {
                slidesToShow: 7,
                slidesToScroll: 1,
                infinite: true,
                dots: false
            }
        },
        {
            breakpoint: 1424,
            settings: {
                slidesToShow: 6,
                slidesToScroll: 1,
                infinite: true,
                dots: false
            }
        },
        {
            breakpoint: 1024,
            settings: {
                slidesToShow: 4,
                slidesToScroll: 1,
                infinite: true,
                dots: false
            }
        },
        {
            breakpoint: 600,
            settings: {
                slidesToShow: 3,
                slidesToScroll: 1,
                infinite: true,
                dots: false
            }
        },
        {
            breakpoint: 480,
            settings: {
                slidesToShow: 2,
                slidesToScroll: 1,
                infinite: true,
                dots: false
            }
        },
        {
            breakpoint: 0,
            settings: {
                slidesToShow: 2,
                slidesToScroll: 1,
                infinite: true,
                dots: false
            }
        }
        // You can unslick at a given breakpoint now by adding:
        // settings: "unslick"
        // instead of a settings object
    ]
});

var filtered = false;
$('.product-button').on('click', function () {
    var filtername = $(this).attr('id');
    var currentclass = $(this).attr('class');
    if (filtered === false) {
        $('.product-carousel').slick('slickUnfilter');
        $('.product-carousel').slick('slickFilter', '.filter-' + filtername);
        $(this).attr('class', filtername + ' product-button');
    } else {
        $('.product-carousel').slick('slickUnfilter');
        $('.product-carousel').slick('slickFilter', '.filter-' + filtername);
        $('.product-carousel').slickGoTo(0);
        $(this).attr('class', filtername + ' product-button');
        filtered = false;
    }
});

When the project loaded on smaller than 1600px width screen it loses the filtering effect. When i click first click button it filters but second and next clicks doesnt filter. If the project loaded on higher than 1600px width screen that filter works nice. And one thing is if i remove responsive option it works ok.
Please help me guys. Thanks your advice

I really like you KENWHEELER

Here is the fiddle demo - https://jsfiddle.net/qzx7aobt/

**Comment by tsbilguun7167** [comment] 2015-09-07 05:28
@kenwheeler help me pls

**Comment by slr1979** [comment] 2015-09-07 12:00
@tsbilguun7167 @kenwheeler - I can confirm that I have the same issue. Removing the responsive option resolves it but I would be grateful for a solution as I need slick to be responsive. Currently using version 1.5.8.

```
		// Slick
		container_slick.slick({
			dots: true,
			infinite: false,
			speed: 300,
			slidesToShow: 6,
			slidesToScroll: 6,
			responsive: [
				{
					breakpoint: 1024,
					settings: {
						slidesToShow: 5,
						slidesToScroll: 5,
						infinite: true,
						dots: true,
					}
				},
				{
					breakpoint: 600,
					settings: {
						slidesToShow: 4,
						slidesToScroll: 4
					}
				},
				{
					breakpoint: 480,
					settings: {
						slidesToShow: 3,
						slidesToScroll: 3
					}
				}
			]
		});
         // Slick Filter
		var $optionSets = $('#filters'),
			$optionLinks = $optionSets.find('a');
		$optionLinks.click(function() {
			var $this = $(this);
			if ($this.hasClass('selected')) {
				return false;
			}
			var $optionSet = $this.parents('#filters');
			$optionSets.find('.selected').removeClass('selected');
			$this.addClass('selected');
			var selector = $(this).attr('data-filter');
			container_slick.slick('slickFilter', selector);
			return false;
		});

**Comment by kenwheeler** [comment] 2015-09-07 12:35
@tsbilguun7167 @slr1979 I'm having a bit of trouble debugging this, as it appears to work in the fiddle. At least, I'm seeing the filtering take place. Are you getting an error in the console? Do you have a clear way that I can reproduce and identify the behavior?

**Comment by kenwheeler** [comment] 2015-09-07 12:40
This is a dupe of #1693 , lets pick it up there

**Closed by kenwheeler** 2015-09-07 12:40 UTC
