### ISSUE TITLE
Unslick() issues

### ISSUE THREAD

**Issue by chrispif** [kenwheeler/slick#469] opened 2014-08-23 04:31 UTC
When a slider is 'unslicked', the .slick-center class is maintained and commands, such as slickPrev and slickNext are still working. Also, when I click on an slick-slide, it triggers the focusOnSelect.

**Comment by kenwheeler** [comment] 2015-01-31 20:35
Dupe of #369

**Closed by kenwheeler** 2015-01-31 20:35 UTC
Labels: Under Investigation
