### ISSUE TITLE
Caption outside its container

### ISSUE THREAD

**Issue by Jorgewlf88** [kenwheeler/slick#2237] opened 2016-04-08 17:00 UTC
How do I catch each caption and put outside of its .slick-slide container? I mean after of .slick-dots. Is it possible?

====================================================================
Here my jsfiddle
https://jsfiddle.net/Jorge_88/h62twv7k/8/

**Comment by leggomuhgreggo** [comment] 2016-04-08 17:09
Hey @Jorgewlf88 Check out `asNavFor` Hope that helps!

Closing: support req, not a bug

**Closed by leggomuhgreggo** 2016-04-08 17:09 UTC

**Comment by Jorgewlf88** [comment] 2016-04-08 17:14
thanks @leggomuhgreggo I'll try
