### ISSUE TITLE
Whitespace issue at the end of slider

### ISSUE THREAD

**Issue by megaslug** [kenwheeler/slick#2149] opened 2016-02-23 12:25 UTC
My carousel container is 400px wide, each slide is 100px wide and in total there are 10 slides. In my settings, I have it set to scroll 4 slides at a time. When I reach the end of the slide, there is undesired  whitespace there.

====================================================================

#### JSFiddle

http://jsfiddle.net/238598/drdydokx/1/

====================================================================

#### Steps to reproduce the problem

Use the following settings
`$(".slider").slick({
      dots: false,
      slidesToShow: 4,
      slidesToScroll: 4,
      autoplay: false,
      infinite: false,
      variableWidth: true,
      centerMode: false,
      initialSlide: 0,
});`

====================================================================

#### What is the expected behaviour?

When clicking 'next' arrow, the slider should check whether there are 4 slides to scroll? If so, go ahead, if not, then scroll the remaining slides.

====================================================================

#### What is observed behaviour?

When clicking 'next', it scrolls through 4 slides at a time even when there might be just 2 slides left to scroll.

====================================================================

#### More Details

This issue is present in 1.5.9 version of slick.js
Tested in Chrome 48.0.2564.116 for Mac

**Comment by leggomuhgreggo** [comment] 2016-02-23 18:19
Hey @megaslug thanks for the solid bug report! I think this is a duplicate of #1968 and related also to this one #1207, which has the most discussion. I'm going to close it, but feel free to give those issues a bump. It's a tricky issue!

**Closed by leggomuhgreggo** 2016-02-23 18:19 UTC

**Comment by mazzaker** [comment] 2016-02-24 08:18
Why you set variableWidth: true if there is a fixed slide width?

[Fiddle](http://jsfiddle.net/drdydokx/2/)

If you need the variableWidth ignore my post ;)

**Comment by megaslug** [comment] 2016-02-24 17:01
@mazzaker I was clearly playing with options trying to find the right combination for the design I was working on. Disabling variableWidth resolved my problem. Thank you very much.

**Comment by jfcartier** [comment] 2017-04-26 04:37
Hi there :)  
Personnally, I wouldn't consider this task as resolved, because I'm currently facing this precise problem. I intentionally need to set the carousel as variableWidth:true and indeed, theres a big white gap at the end. Not very clean, so if you guys have any workaround for me, I'll take it :)

Thanks a lot

**Comment by mazzaker** [comment] 2017-04-27 06:25
Can you please build a small fiddle with the slides width you want to use.

**Comment by jfcartier** [comment] 2017-04-27 06:31
Sure! http://jsfiddle.net/drdydokx/26/
I think the proper behaviour would be to limit the movement when the last element has reached the right side, so we can avoid that unwanted white space

**Comment by groomain** [comment] 2017-05-05 16:29
I have the same issue. I would like to finish the slider when the last slide reach the right of the slider.

Any idea to solve this?

Regards,

**Comment by jfcartier** [comment] 2017-05-05 16:41
@groomain , there's a (bugged) workaround here #2635. But the author doesnt seem to plan to fix it anytime soon. 
In my case, this is a huge problem and I'm thinking about using another library.. even if I love slick.

**Comment by groomain** [comment] 2017-05-09 07:43
@jfcartier Thanks a lot. This PR https://github.com/kenwheeler/slick/pull/2635 is exactly what I needed.

Regards,

**Comment by foysalremon** [comment] 2018-03-21 17:57
I have a fix which may help for now now [https://codepen.io/foysalremon/pen/KoWjLg](url)

**Comment by jfcartier** [comment] 2018-03-21 18:00
@foysalremon, your link isnt working

**Comment by foysalremon** [comment] 2018-03-21 18:16
@jfcartier My mistake, I have updated the link.

**Comment by RetroCIB** [comment] 2019-04-02 09:55
Slick.prototype.getLeft : 

> [..]
//
        var listSlides = _.$slides,
            widthList = _.listWidth,
            widthSliders = 0;
//
        for (var index = 0; index < listSlides.length; index++) {
            widthSliders += listSlides[index].offsetWidth;
        }
//
        if(widthList > widthSliders){
            targetLeft = -0;
        }else if( - targetLeft + widthList > widthSliders){
            targetLeft = - ( widthSliders - widthList );
        }
  //
        return targetLeft;

**Comment by hafidk** [comment] 2019-04-02 10:08
For mobile devices, setting swipeToSlide to false and slidesToScroll / slidesToShow having the same value solved the issue.

**Comment by Takhine** [comment] 2019-10-25 16:47
What worked for me was to do the following:
1) set margin auto on the images within the slick-container i.e margin: auto (only works if image has a defined width)
2) set a constant left value to the left arrow i.e left: -40px
3) set a constant right value to the right arrow i.e right -50px

Hope this helps.
Cheers!
![Capture2](https://user-images.githubusercontent.com/20356668/67588992-13fb9580-f775-11e9-975b-bd5dd50f3984.PNG)

**Comment by dajanvulaj** [comment] 2019-11-18 18:54
Setting the slidesToShow option to nrSlides - 1 seems to work.
Hope this helps.

	var $slickSlider = $("#slickSlider");
	
	//On Init
	$slickSlider.on("init", function(event, slick){
		var slidesToShow = slick.originalSettings.slidesToShow;
		var nrSlides = slick.slideCount - slidesToShow;

		setTimeout(function(){
			$slickSlider.slick('slickSetOption', 'slidesToShow', nrSlides);
		}, 500);
	});

	$projectsSlider.slick({
		variableWidth: true
	});

**Comment by fedegilles** [comment] 2020-08-11 14:37
I was running into the same problem and by just adding **"variableWidth: true,"** solved it. 

The hole js code:

$(document).ready(function() {

        $('.prods-wrapper').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        variableWidth: true,
        nextArrow: $('.next'),
        prevArrow: $('.prev'),
        });

        });

**Comment by isahohieku** [comment] 2020-11-24 16:46
This worked for me

`.slick-initialized .slick-slide {
  display: flex;
  justify-content: center;
}`
