### ISSUE TITLE
centeredMode:true and slidesToShow: 2

### ISSUE THREAD

**Issue by rgblab** [kenwheeler/slick#2441] opened 2016-07-28 09:05 UTC
basically, i need to style two slides that are cutted off when centerPadding is set. and issue is that class **slick-active** is assigned to two visible slides and one that is half visible, on the right only when even nubmer is set for slidesToShow. so, pattern is as follows

slidesToShow: 1 => active class on 1 slide
slidesToShow: 2 => active class on 3 slides /* HERE */
slidesToShow: 3 => active class on 3 slides
slidesToShow: 4 => active class on 5 slides /* HERE */
slidesToShow: 5 => active class on 5 slides

here is a link to code pen: https://codepen.io/rgblab/pen/yJEQKq

expected is to have same number of active classes as slidesToShow variable is set.

**Comment by leggomuhgreggo** [comment] 2016-07-28 17:45
Fair point.

**Comment by mehas** [comment] 2016-09-06 19:00
For now, as a workaround (at least for styling) you can leverage the adjacent sibling selector to select the slides that incorrectly receive the `.slick-active` class. 

Examples (assuming `slidesToShow` = `2`, but 3 slides are getting the active class):

```css
.slick-active { /* active slide styles */}
.slick-active + .slick-active + .slick-active { /* inactive slide styles */}
```

```js
function fixActiveClassCallback() {
   $('.slick-active + .slick-active + .slick-active').removeClass('.slick-active');
}
```

**Comment by leggomuhgreggo** [comment] 2016-09-16 12:57
This is a duplicate of #1571 it turns out. Closing in favor of the other issue. Thanks!

**Closed by leggomuhgreggo** 2016-09-16 12:57 UTC
Labels: Bug: Confirmed, Feature: Center Mode
