### ISSUE TITLE
Miscalculated width of slides track on variableWidth with progressive lazy load

### ISSUE THREAD

**Issue by NinjaBCN** [kenwheeler/slick#790] opened 2014-11-15 15:49 UTC
Hi Ken, 
First of all - great plugin, fantastic work, respect!

However, with the new feature "variableWidth" combined with progressive lazy load and centerMode, I encountered problems when having higher amount of image slides in the slick (ca 100+).

The width of "slick-track" element on first few calls to setDimensions seems to be miscalculated - track is slightly shorter than it should be, as the images while initializing do not give correct slide width to the slick. 

The effect of this issue is fairly bad: slide-track expands for two rows (as the fully loaded images can not fit within miscalculated track width).

After while (when all progressive images are fully initialized), all is getting back OK, f.e. after first slide change all gets finally calculated correctly and slick is looking fine.

I did not have a time to dive deeper in your code, so i just created kind a dirty hack to fix it (see bellow), but I think this issue shall be addressed and get resolved more elegant way.

The merit of my hack is simple:

1) it simply checks the slick-track width on every call to setDimensions, and compares previously calculated width with the newly calculated.  if it differs (width changes as the lazy loading images still continue initializing), it sets the track width manually for INSANE value, e.g. 500000 (to surely accommodate all slides).

2) Once slick-track width stabilizes (previously calculated width equals to new), all returns to normal and manually setting the insane width is bypassed. Track has correct width, and looks good.

As the process is quite quick, the hack does not have any bad influence on initial display, the slick simply starts "fixed" as it would normally, but it is really dirty hack. ;-)

THE HACK

First, I created new var for storing the slick-track width (at line ca 144):
            _.lastTrackWidth = 0;

Than, I modified the setDimensions method, inside >variableWidth === true< condition (line ca 1335):

        } else if (_.options.variableWidth === true) {
            var trackWidth = 0;
            
            // *** edit
            // *** HACK for miscalculated track width while progressive lazyLoad (wrong slide widths)
            if (_.options.lazyLoad == "progressive" && _.$slideTrack.width() !== _.lastTrackWidth ) {
	            trackWidth = 500000;
            }
            // *** END edit
            
            _.slideWidth = Math.ceil(_.listWidth / _.options.slidesToShow);
            _.$slideTrack.children('.slick-slide').each(function(idx){
                trackWidth += Math.ceil($(this).outerWidth(true));
            });
            _.$slideTrack.width(Math.ceil(trackWidth) + 1);
           
            // *** edit
            // *** HACK for miscalculated track width while progressive lazyLoad (wrong slide widths)
            _.lastTrackWidth = Math.ceil(trackWidth) + 1;
            // *** END edit
  
        } else {

Please, I am sure you will have better idea, and I hope in a mean time the above may help somebody to resolve this issue in a dirty way, before fixed in source.

Thanks

**Comment by chrisdatlas** [comment] 2015-01-05 17:59
I was able to work around this issue by adding a min-width of 100% to the .slick-track. If you need to get this to work and are unsure of how to accomplish it with js, I would give that shot.

**Comment by that1guy** [comment] 2015-01-07 06:57
Thanks @chrisdatlas, this didn't work for me though.  Here's demonstration of what I see.  Any help here would be great.  I'm kinda going bonkers as demo day get's closer and closer. :) http://jsfiddle.net/bnbq7nq4/6/

**Comment by chrisdatlas** [comment] 2015-01-09 23:02
Hey @that1guy, sorry you didn't have any luck with the min-width. For whatever reason that seems to have resolved the incorrect sizing of the .slick-track on my site. I'll try to take a look this weekend to see if I can come up with another workaround.

**Comment by virtual** [comment] 2015-01-22 14:21
Thanks @chrisdatlas, adding the min-width of 100% to .slick-track worked for me; now they aren't stacking small images anymore

**Comment by that1guy** [comment] 2015-01-24 02:14
Hi @kenwheeler, noticed this is slated for 1.4 bug fix.  Any estimation of when this milestone might be hit.  Thanks very much!

**Comment by kenwheeler** [comment] 2015-01-24 02:19
@That1guy starting this weekend

**Comment by that1guy** [comment] 2015-01-24 05:25
@kenwheeler nice! :+1:

**Comment by kenwheeler** [comment] 2015-01-29 02:35
Fixed on dev

**Closed by kenwheeler** 2015-01-29 02:35 UTC
Labels: Confirmed Bug

**Comment by that1guy** [comment] 2015-01-29 04:03
Hi @kenwheeler.. Please do call me a dummy if I'm being one, but I don't see dev branch.  :) Where can I grab this fix from?

**Comment by kenwheeler** [comment] 2015-01-29 04:03
I'm in the process of finishing up the docs and releasing 1.4. We're talking like 20 minutes here.

**Comment by that1guy** [comment] 2015-01-29 04:04
oop! Sorry man!  All good.

**Comment by that1guy** [comment] 2015-02-08 06:03
@kenwheeler Just writing to say thank you.  This resolved my issue.  you rock!

**Comment by krishna9960** [comment] 2015-02-17 14:18
If i make VariableWidth true the last slide slides down to form a new row just by one pixel but if i inspect it and increase the width of .slideTrack class it sets to one row and works perfectly.


Can you help me with this issue @kenwheeler

**Comment by kenwheeler** [comment] 2015-02-18 18:26
@krishna9960 can i see a jsFiddle of your settings.

**Comment by vjnunez** [comment] 2015-02-24 15:05
Hey guys, im having this exact same problem and im using 1.4.1.
```javascript
$('#hotel-details-modal .gallery').slick({
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    centerMode: true,
    variableWidth: true
  });
```
Images stack vertically at page load but if i make any interactions with the carousel it gets fixed, weird, any ideas?

**Comment by kenwheeler** [comment] 2015-02-26 13:11
@vjnunez is your slider hidden at first?

**Comment by artmanPT** [comment] 2015-03-05 01:01
Hi

Im having the same problem. And also using 1.4.1

With my basic knowledge I've tried to replicate it here:
https://jsfiddle.net/ArtmanPT/evg9ymxp/42/
(i've used the same number of images and proportions - w/h ratio - as my project)

Only appears when the window size is below +/-1000 px. 

In my project the slider is not hidden. 
...and adding the min-width of 100% to .slick-track didn't worked for me.

I hope this can help you.

**Comment by amgadfahmi** [comment] 2015-03-05 06:04
@kenwheeler greta components man
But am facing a problem on the phone with the following settings 
  $('.slickCarousel').slick({
   lazyLoad: 'ondemand',
  dots: true,
  infinite: false,
  speed: 300,
  slidesToShow: 1,
  centerMode: true,
  variableWidth: true ,
  adaptiveHeight: true,
  autoplay: true 
  });
All the images have been cropped with the same height 500px  but it have a lagging in the movements when it comes to phone screen and screw the order of the pictures are showing and sometimes it repeat the first image. I have tried different settings but all have the same problem on the phone that the movement is not correct. Would appreciate your response.

**Comment by rorykoehler** [comment] 2015-03-14 21:40
I'm having the same issue using the latest jquery-slick-rails gem .  At certain breakpoints the images start stacking in rows like Emma's (16th Nov) except you can see the whole image on both (or some times all 3) rows. My settings are:

$('.cat_caro').slick({
  dots: false,
  infinite: true,
  speed: 300,
  slidesToShow: 1,
  centerMode: true,
  variableWidth: true
});

.slick-track width is too narrow and gets calculated fresh each time the image slides. If I manually widen .slick-track in developer tools then the issue resolves itself.

**Comment by iamhexcoder** [comment] 2015-03-20 19:53
Having this issue as well with v1.4.1, same thing as @rorykoehler : .slick-track seems to be one slide too narrow. If I add a slide width to the amount in the inspector, things are working peachy. 

Slider Settings:
```javascript
$('.event-slider-slides').slick({
    dots: true,
    appendDots: '#event-slider-controller',
    draggable: false,
    variableWidth: true,
    adaptiveHeight: false,
    infinite: false
});
```

**Comment by rorykoehler** [comment] 2015-03-21 17:33
@iamhexcoder upgrade to the latest version 1.5.0.1 https://github.com/bodrovis/jquery-slick-rails 

It seems to have rectified all my issues :)

**Comment by iamhexcoder** [comment] 2015-03-22 01:40
@rorykoehler I'm using the non-rails version, pulled from the official github repo via composer - but maybe I will try to sift through this rails version

**Comment by kenwheeler** [comment] 2015-03-22 01:43
1.51 will be released soon

**Comment by rorykoehler** [comment] 2015-03-22 12:31
@kenwheeler Thanks for an awesome carousel. 

Just to let you know the issue still occurs if the image is ridiculously wide (ie much wider than 100% width of the screen). It's not a huge problem as images generally won't be that wide but it would be nice for it to work from a mobile touch perspective. In my use case the carousel still bumps the images down when photographer uploading the files uploads an image that consists of 3 related images grouped together side by side into one image file (panorama style). I wouldn't say it's a priority issue as it works fine with more normal width images and I think I have a work around for this in any case (though still have to try it out).

**Comment by thedamon** [comment] 2015-04-30 20:22
Having an issue similar that's similar, but the dimensions of the sliders are coming out absolutely huge in only in IE8 and only in the production environment.

slick-slider classes are getting widths of 3500+ pixels and growing each time the slider slides.

It works in an isolated test case and on our mockups, so I can't isolate what's causing this, except possibly the speed at which the images are loading. 

Wondering if anybody has an idea of what could be causing this or how to work around it

**Comment by owlyowl** [comment] 2015-05-06 04:55
Having that same issue seen on smaller screens like so:
![image](https://cloud.githubusercontent.com/assets/1916426/7487696/d1abe45a-f3ff-11e4-824c-b92816ad5a5f.png)

Just wondering what the best way to deal with this would be?
we're using:
 $(this).slick(
                $.extend({
                    arrows: true,
                    infinite: true,
                    lazyLoad: 'ondemand',
                    dots: true,
                    slide: '.slide-item',
                    slidesToShow: window.defaultSlidesToShow,
                    slidesToScroll: window.defaultSlidesToShow,
                    responsive: [
                        {
                            breakpoint: 1280,
                            settings: {
                                slidesToShow: window.desktopSlidesToShow,
                                slidesToScroll: window.desktopSlidesToShow
                            }
                        },
                        {
                            breakpoint: 820,
                            settings: {
                                slidesToShow: window.tabletSlidesToShow,
                                slidesToScroll: window.tabletSlidesToShow
                            }
                        },
                        {
                            breakpoint: 580,
                            settings: {
                                slidesToShow: window.mobileSlidesToShow,
                                slidesToScroll: window.mobileSlidesToShow
                            }
                        }
                    ]
                }, $(this).data('slick')));
        });

**Comment by emmawinston** [comment] 2015-05-08 16:45
I'm experiencing a slightly different behaviour in 1.5.0, Firefox 37.0.1, only in Firefox, only in variable width sliders.
Should load like this: 
![screen shot 2015-05-08 at 17 42 44](https://cloud.githubusercontent.com/assets/6143053/7541010/c5fcbe9e-f5a9-11e4-9faa-934f4724a482.png)

Instead loads like this:
![screen shot 2015-05-08 at 17 39 41](https://cloud.githubusercontent.com/assets/6143053/7541016/d4b0a57c-f5a9-11e4-8b8a-96e9c1825c2b.png)

But not always, very inconsistently.

Looking at the slick-track it's getting widths over 5000 pixels as thedamon describes above. Any help appreciated!

**Comment by alvinpascoe** [comment] 2015-05-16 18:33
I also found I was having issues with the carousel expanding to extremely large widths (and breaking page layout).

At first I came up with a fix to force a carousel container width (based on the $(window) width) but then I found the real source of my problem.

The issue was being caused by a clearfix on a parent container (it wasn't the immediate parent, but about 4 or 5 levels up).

After removing the clearfix, the carousel behaved as expected!

**Comment by lukefrake** [comment] 2015-06-11 11:22
This is why I love open source projects, I find a bug, I come to raise a bug, I find a patch solution, I update and everything works. Much thanks @kenwheeler - Great project!

**Comment by larzilla** [comment] 2015-07-02 18:54
I was having this same issue. My fix was similar to @alvinpascoe.  One of the parent elements was set to display:table. Once I changed this parent to display:block, the issue was solved.

**Comment by matdave** [comment] 2015-07-16 20:36
Thanks @larzilla that was my issue too!

**Comment by shabirmanu** [comment] 2015-08-26 16:17
Hello Ken,

I am getting the same issue, but I am using vertical carousel. It initially calculate wrong height. How can I fix this. Also I would like to start a child slider on that slide which has slick-current class. How can I achieve this. Please help me on this.

Thanks

**Comment by zahidmak** [comment] 2015-11-16 21:12
Is there any resolution to the slick-track not being wide enough hence multiple rows of tracks? If anybody has hot fix then please let me know.

**Comment by ahnbizcad** [comment] 2015-12-17 17:25
not sure if this is an issue anymore, but I thought I'd share what I did.

on line 500 or so, I changed

`if ($(window).width() < _.breakpoints[`

to 

`if (window.innerWidth < _.breakpoints[`

and in my app's code, used 

`window.innderWith` as well

**Comment by zahidmak** [comment] 2016-01-11 16:45
Thanks @ahnbizcad I will give a shot.

**Comment by iorrah-gonzalez** [comment] 2017-05-24 13:03
In case someone is still facing this issue, check out this question:
https://stackoverflow.com/questions/43216603/slick-initial-width-calculation-incorrect

**Comment by gnana2315** [comment] 2018-03-22 06:55
![screenshot 2](https://user-images.githubusercontent.com/26135923/37755504-c03e371e-2dcb-11e8-99d9-9c98f2b49e05.jpg)
i'm using slick slider on tab. it's works well but, only on 1st tab. it's mean slick-track class width will be 0 for 2nd and 3rd tabs.

how can i solve this plz help me

**Comment by AnwerAR** [comment] 2018-05-02 17:38
The below piece of CSS worked for me.

```
.slick-initialized .slick-slide {
    padding: 0;
}
```
