### ISSUE TITLE
Responsive unslick cause carousel not to initialize carousel when changing back to previous breakpoint

### ISSUE THREAD

**Issue by rcreate** [kenwheeler/slick#2473] opened 2016-08-16 11:59 UTC
If I set mobileFirst: true and tell slick to "unslick" on breakpoint 0, the carousel is unslick'd correctly.
But if I change back to tablet or desktop view the expected behaviour is that slick should be instantly enabled. This don't happen for some reason.

====================================================================

#### jsFiddle
https://jsfiddle.net/rcreate/0ffunxeh/

====================================================================

#### Steps to reproduce the problem

1. Run the fiddle in fullscreen
2. Resize window till carousel is unslick'd (~ 1000px)
3. Resize window to full width (e.g. 1920px)

====================================================================

#### What is the expected behaviour?

Slick carousel should be initialized and the items should be toggleable horizontal

====================================================================

#### What is observed behaviour?

slick is permanently unslicked till a refresh of the whole page

====================================================================

#### More Details

- All browsers (e.g. firefox, chrome, ...)
- Version 1.6.0
- Did not work before

**Comment by leggomuhgreggo** [comment] 2016-08-16 20:40
Hey @rcreate this is a duplicate of a known issue. Search existing issues to learn more. Thanks!

**Closed by leggomuhgreggo** 2016-08-16 20:40 UTC

**Comment by tenold** [comment] 2017-11-09 23:21
Can you please link to the duplicate issue?

**Comment by amoshydra** [comment] 2018-01-16 07:50
@tenold could be this https://github.com/kenwheeler/slick/issues/2753

Seems like we need to reinit after the item has been `unslick`
