### ISSUE TITLE
Prev and next buttons not showing up in safari 7

### ISSUE THREAD

**Issue by Turqueso** [kenwheeler/slick#2101] opened 2016-02-05 19:00 UTC
Safari 7.0.6
OS 10.9.5

**Comment by leggomuhgreggo** [comment] 2016-02-05 20:03
Hey @Turqueso I was about to close this, because there was no test case provided, [per the contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), but I checked on crossbrowsertesting using the [repos boilerplate fiddle](http://jsfiddle.net/simeydotme/fmo50w7n/) and confirmed the issue [[Screenshot](http://i.imgur.com/yxUSYv3.png)]

When I inspected, the markup for the arrows didn't seem to be loading into the dom [[screenshot](http://i.imgur.com/zymLVjg.png)], but no errors in the console that were obvious to me [[screenshot](http://i.imgur.com/MG5MXNk.png)]

Will try to look into later. Thanks!

**Comment by Turqueso** [comment] 2016-02-05 22:07
@leggomuhgreggo I did notice the markup for the arrows didn't show up and there were no errors on console, but I missed the guidelines, I'm sorry.  thanks for looking into it anyway!

**Comment by simeydotme** [comment] 2016-02-06 16:32
Seems there's a bunch of problems being mentioned about jQuery and Safari 7 on Mavericks... another great example of Apple fucking shit up on the web. #useless

**Comment by simeydotme** [comment] 2016-02-06 16:37
However, I'm not sure our policy on supporting old browsers with compatibility issues with jQuery...
If @Turqueso can pinpoint his version of jQuery and test on another version of jQuery that'd be great. 

https://blog.jquery.com/2014/12/18/jquery-1-11-2-and-2-1-3-released-safari-fail-safe-edition/

**Closed by simeydotme** 2016-02-06 16:37 UTC
Labels: Bug: Confirmed

**Comment by Turqueso** [comment] 2016-02-10 22:26
it's working now, I didn't change anything so i'm confused, damn it safari!

**Comment by leggomuhgreggo** [comment] 2016-02-11 04:02
Hmm, thats interesting--it's still not working when I test.

**Comment by inlikealion** [comment] 2016-05-25 16:12
I've got this same issue. Works locally for me in a rails app, but on our QA server it applies most of the Slick dom but _NOT_ the arrows markup, and is not functional despite throwing no errors. Unfortunately there is no public access to this server.
