### ISSUE TITLE
update height on item click and responsive breakpoint issue

### ISSUE THREAD

**Issue by n0xx** [kenwheeler/slick#1496] opened 2015-07-01 14:23 UTC
Hi guys, first of all you made a great plugin but i can't figure out one thing.
I have horizontal slide with 100% for each slider and adaptiveHeight - everything works great but:

In every slide i have tabs with different height and adaptiveHeight calculate height of slider from first tab not the highest so when i click second tab i can see only part of it.
It's updating height after i move slightly slide but it's not updating auto.

Is there a way to somehow autoupdate height if slide when user click something in slide ?

Second thing is responsive option, its working great when i scaledown site but when i load site in small width let's say 500px script somehow stop working and slick is not working anymore.

My config:

//THUMBS
$('#ekspresyWrapperMenu').slick({
        slidesToShow: 5,
        slidesToScroll: 1,
        asNavFor: '#ekspresyWrapper',
        dots: false,
        arrows: false, 
		focusOnSelect: true,
		centerMode: true,
		infinite: true,
    responsive: [{ 
        breakpoint: 700,
        settings: {
      slidesToShow: 2,
        slidesToScroll: 1
        } 
    }]
});

//SLIDER
$('#ekspresyWrapper').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: true,
		adaptiveHeight:true,
		draggable:true,
        asNavFor: '#ekspresyWrapperMenu',
	    prevArrow:"<span id='ekspresyWrapperPrev'></span>",
        nextArrow:"<span id='ekspresyWrapperNext'></span>"
});

Could someone help ?

**Comment by ShrmnK** [comment] 2015-07-04 07:53
I'm having trouble understanding your situation. Could you create a jsfiddle or similar to show an example of what the issue is and what you are trying to achieve?

**Comment by leggomuhgreggo** [comment] 2016-01-26 07:48
Closing because there is no fiddle. If you make one we can look at reopening. Thanks!

**Closed by leggomuhgreggo** 2016-01-26 07:48 UTC
