### ISSUE TITLE
Dots keep appearing even if it's one slide Version 1.7.1

### ISSUE THREAD

**Issue by saxatile** [kenwheeler/slick#3059] opened 2017-08-17 07:59 UTC
> short description of the bug / issue, provide more detail below.
Dots keep appearing even if it's one slide "this problem if not mistaken appears only on 1.7.1 version I had to downgrade to 1.6.0 to get rid of the dots. thanks and all the best to slick team nice job!! "
====================================================================

###### `[  paste your jsfiddle link here  ]`  

This is my jsfiddle-link:
http://jsfiddle.net/fmo50w7n/1350/

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. Add a single slide to the slider
2. set `dots: true`
3. Run the script ;)

====================================================================

#### What is the expected behaviour?

For single-slide sliders the dot-navigation should be hidden

====================================================================

#### What is observed behaviour?

Dot-navigation are added, even if there is only one slide in the slider.

====================================================================

#### More Details

- Which browsers/versions does it happen on? *
- Which jQuery/Slick version are you using? 1.7.1
- Did this work before? When downgrading to 1.6 it works as expected.

**Comment by saxatile** [comment] 2017-08-21 11:21
I updated my bug-descreption. Thx.

**Comment by saxatile** [comment] 2017-08-21 14:23
it seems like it thanks for your effort Sir!

**Comment by leggomuhgreggo** [comment] 2017-09-12 12:42
Should be fixed now. Thanks!

**Closed by leggomuhgreggo** 2017-09-12 12:42 UTC

**Comment by afalchi82** [comment] 2017-12-12 08:42
Uhm, I still get it with version 1.8.1

**Comment by timdiacon** [comment] 2018-01-04 15:46
I'm also getting this issue with anything above 1.6

**Comment by davidloop** [comment] 2018-02-02 16:21
Version 1.8.1 solves this problem. However, OP has only updated slick.js and not slick.min.js. Use slick.js in your stack for now.

**Comment by Ant-Pavel** [comment] 2018-02-03 21:12
Use ":only-child"  selector

**Comment by bonovski** [comment] 2018-04-06 06:49
This issue still persists in the min.js versions hosted on various CDNs.
I do find it hard to understand why the two files are not identical.

**Comment by bridgetwes** [comment] 2018-08-06 21:16
Noting this issue still persists in the min.js version. Works perfectly - even with slidesToShow settings at different breakpoints with the slick.js (non minified) version.

**Comment by fritzmg** [comment] 2018-12-06 09:34
I can confirm that this issue still presists in the distributed minified version.

**Comment by shellygraham** [comment] 2018-12-28 20:21
Thanks for posting a solution for this. The min.js version problem still exists.

**Comment by tourniquet7** [comment] 2019-01-23 20:32
If you can't easily upgrade your slick, you can use this .scss

```
.slick-dots {	
		> li {
			display: none;
		}	
	
		> li ~ li {
			display: inline-block
		}
	}
```

**Comment by CaliJens** [comment] 2019-01-30 10:37
With above solution you don't display the first dot when there are multiple slides.
If you want a solution with .scss use following:
`
.slick-dots {
    > li {
        display: inline-block;
    }

    > li:only-child {
        display: none;
    }
}
`

**Comment by erthi16** [comment] 2019-03-19 15:45
Hello to all!

Do you have an idea when the minified version will be available?

Thanks!

**Comment by erthi16** [comment] 2019-03-21 13:04
Just to let you know... We've used the non minified version but our custom inline styles on each of our slides were removed between 768px and 1199px by the slick scripts... The minified version of slick does not have the bug... Can anyone confirm?

**Comment by samuelecarpene** [comment] 2019-09-30 09:46
What about to release the functionality in the minified version too?

**Comment by wecreatedigital** [comment] 2020-04-08 15:35
This is still a bug - switching to the non-minified version resolves the issue for us. We compile everything using Yarn so we don't necessarily need the minified version but that was a decent hour I'll never see again! 🙃

**Comment by kunal-sin** [comment] 2020-04-15 16:30
The problem is with the **slick-dotted** class which is getting added even if there is one item in the slick. and **slick-dotted** class is adding margin-bottom of 30px.
@wecreatedigital Thanks for the suggestion, switching to the non-minified version resolves the issue for me as well.

**Comment by gavin310** [comment] 2021-03-31 16:15
> This is still a bug - switching to the non-minified version resolves the issue for us. We compile everything using Yarn so we don't necessarily need the minified version but that was a decent hour I'll never see again! 🙃

Thanks! I just grabbed the non-minified .js file (https://raw.githubusercontent.com/kenwheeler/slick/master/slick/slick.js) and ran it through https://javascript-minifier.com and now it works perfectly.

**Comment by neelam-chaudhary10** [comment] 2023-01-02 11:36
Hi
This issue has been solved in the master branch but there is no new tag released with the fixed minified version. Can we please reopen this until there is a new tag release.
