### ISSUE TITLE
Inline-Style on arrows -> "display: block" (hiding arrows)

### ISSUE THREAD

**Issue by Jugibur** [kenwheeler/slick#1457] opened 2015-06-19 06:51 UTC
I want to hide the left arrow on the first slide,
and the right arrow on the last slide.

Why do you use an inline-style "display: block" on each arrow?

Overwriting with external CSS is possible, yes, but you need a high specification with "!important".
Perhaps you can set "display: block" in the external slider-css?

**Comment by boRk3D** [comment] 2015-07-21 12:31
+1
is this working as intended?

**Comment by simeydotme** [comment] 2015-07-21 16:37
yes, it's been this way a long time. I was tempted to change it in a recent patch, but didn't do it in the end.

https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1288-L1289
Feel free to make a patch with loaded/unloaded arrow & dot classes :)

**Comment by leggomuhgreggo** [comment] 2016-05-26 01:09
Looks like this got into the master at some point. Closing! Thanks!

**Closed by leggomuhgreggo** 2016-05-26 01:09 UTC
Labels: Invalid: Out of Date

**Comment by TheNaderio** [comment] 2018-07-17 10:04
Is this really done? I still got this error in 2018. The `slick-arrow` is automatically given `display:block` as an inline statement.
And I really dont like `!important`in my Styles ;)

This:
```
mySlider = $('.my-slider').slick({
        vertical: true,
        swipe: false,
        infinite: false,
        slidesToShow: 4,
        slidesToScroll: 1,
        speed: 250,
        prevArrow: '<div class="slick-prev-wrap"><button type="button" class="slick-prev"><i class="far fa-chevron-up"></i></button></div>',
        nextArrow: '<div class="slick-next-wrap"><button type="button" class="slick-next"><i class="far fa-chevron-down"></i></button></div>'
    });
```
Generates this:
```
<div class="slick-prev-wrap slick-arrow slick-disabled" aria-disabled="true" style="display: block;">
    <button type="button" class="slick-prev"><i class="far fa-chevron-up"></i></button>
</div>
```

**Comment by VincentCharpentier** [comment] 2018-10-04 08:45
Same here, 

I'm working with computed slides; In one of my scenarios 5 slides are displayed, then filtered with slick filters and I end up having only 1 slide with `slidesToShow: 4`, no arrow needed.

```html
<div class="arrow arrow-right carousel_ready slick-arrow slick-hidden" style="display: block;" aria-disabled="true" tabindex="-1"></div>
```

`.slick-hidden` + `display:block` should not happen

note: `display:block` after a window resize

**Comment by TheNaderio** [comment] 2019-02-03 16:12
This should be reopened.
Feb. 2019 - and the issue is still present.

No weird magic in my initialisation code:
```
$('.upcoming-events--slick-wrap').slick({
    mobileFirst: 1,
    infinite: false,
    slidesToShow: 1,
    prevArrow: "<button type='button' class='upcoming-events--slick-prev slick-arrow'><i class='fas fa-angle-left'></i></button>",
    nextArrow: "<button type='button' class='upcoming-events--slick-next slick-arrow'><i class='fas fa-angle-right'></i></button>",
    responsive: [
        {
            breakpoint: 768,
            settings: {
                slidesToShow: 2
            }
        },
        {
            breakpoint: 992,
            settings: {
                slidesToShow: 3
            }
        },
        {
            breakpoint: 1200,
            settings: {
                slidesToShow: 4
            }
        }
    ]
});
```


Generates this - with an inline style `display: block;`...
```
<div class="slick-prev-wrap slick-arrow slick-disabled" aria-disabled="true" style="display: block;">
     <button type="button" class="slick-prev"><i class="far fa-chevron-up"></i></button>
</div>
```

**Comment by teetotum** [comment] 2020-11-24 10:26
This error is still present. And it's so weird. I perused the code in master and did find nothing that explains it.
Is there any third party lib used in the slider that might cause it? jQuery maybe?

**Comment by dennisbohn** [comment] 2023-06-03 22:01
The problem occurs due to the use of [jQuery function "show"](https://api.jquery.com/show/) in the initUI function.

```javascript
    Slick.prototype.initUI = function() {

        var _ = this;

        if (_.options.arrows === true && _.slideCount > _.options.slidesToShow) {

            _.$prevArrow.show();
            _.$nextArrow.show();

        }

        if (_.options.dots === true && _.slideCount > _.options.slidesToShow) {

            _.$dots.show();

        }

    };
```

If you want to style "display" yourself, you have to remove the corresponding property.

```javascript
    Slick.prototype.initUI = function() {

        var _ = this;

        if (_.options.arrows === true && _.slideCount > _.options.slidesToShow) {

            _.$prevArrow.css("display", "");
            _.$nextArrow.css("display", "");

        }

        if (_.options.dots === true && _.slideCount > _.options.slidesToShow) {

            _.$dots.css("display", "");

        }

    };
```
