### ISSUE TITLE
Better Touchsupport

### ISSUE THREAD

**Issue by Defcon0** [kenwheeler/slick#2187] opened 2016-03-07 20:56 UTC
Hello folks,

at first a big thanks to kenwheeler for the great plugin. Only one thing is a bit annoying: I cannot swipe *quickly* through the slides. When trying to slide left a slide at the moment this particular slide is animated to the left, this is simply not possible. I have to wait until the animation of the sliding is finished. This slows down the speed of interaction a bit.

Is there any way to imrove that? In this slider fast interaction is done a bit more smoothly as an example: http://www.jssor.com/demos/image-slider.slider

**Comment by leggomuhgreggo** [comment] 2016-03-11 08:02
@Defcon0 Interesting idea! Looks like a duplicate of #2186 so I'm going to close this one. Thanks!

**Closed by leggomuhgreggo** 2016-03-11 08:02 UTC
Labels: Enhancement
