### ISSUE TITLE
No response when using browser maximise

### ISSUE THREAD

**Issue by two2clicks** [kenwheeler/slick#656] opened 2014-10-15 14:30 UTC
Hi,

When resizing the browser window by dragging, the responsive change are applied correctly.

But when going from a small window to full screen by clicking 'maximise' the changes are not applied correctly, leaving an incorrectly sized slider.

**Comment by kenwheeler** [comment] 2015-01-24 20:02
Closing because I can't reproduce, and even if I could, I would have to do polling, which I'm not doing in core.

**Closed by kenwheeler** 2015-01-24 20:02 UTC
Labels: Confirmed Bug
