### ISSUE TITLE
Enable on certain break points (after disabling)

### ISSUE THREAD

**Issue by jackbarham** [kenwheeler/slick#1656] opened 2015-08-19 15:37 UTC
I'm really stuck with an issue. I want to disable slick below 500px, I can get it to disable (so the HTML stacks nicely), but when I drag the browser past 500px it wont re-initiate unless I refresh, is there a way around this?

```javascript
$('.slick').slick({
    autoplay: true,
    autoplaySpeed: 4000,
    delay: 5000,
    speed: 700,
    responsive: [
        {
            breakpoint: 500,
            settings: "unslick"
        }
    ]
});
```

**Comment by cassiocardoso** [comment] 2015-08-19 22:28
Have you tried to re-initiate using window.resize?

**Comment by sthzg** [comment] 2015-08-21 09:15
Same here, once it unslicks it doesn't reslick, so to speak. :) Is this supposed to work or by design?

**Comment by jackbarham** [comment] 2015-08-21 09:18
Thats the problem I am having. It will stop Slick and collapse the div's on top of each other, but then I drag out it wont re-initiate unless I refresh. Here is the project, I am finishing off:

http://www.cradle.agency
user: flywheel
pass: cradleagency

**Comment by LucaBL** [comment] 2015-08-22 13:35
I have very similar settings as in the first post, unless i use mobileFirst as well. I want a carousel on small screens and no carousel on greater widths.
I was using version 1.5.0, and the "unslick-reslick" switch, while constantly trying changing the screen width, was working perfectly.

But, I had to update because it destroyed the event listeners of the content of the slides every time it changed, and now with 1.5.7 it doesn't work. It 'unslicks' fine, but doesn't 'reslick' anymore.

**Comment by smonn** [comment] 2015-08-27 08:52
[See this JSFiddle](http://jsfiddle.net/nw4v2187/1/). It works in 1.5.1, but not in 1.5.2 and above.

**Comment by jackbarham** [comment] 2015-08-27 09:20
A friend of mine (who know more about JS than I do) helped me fix my issue. I his words "this is a massive hack" so I wont put his name to it, but it does work, if anyone else can fine tune it further:

```javascript
(function() {
    var slickSettings = {
        autoplay: true,
        autoplaySpeed: 4000,
        delay: 5000,
        speed: 700
    };

    var $slick = $('.slick');

    if (!$slick.length) {
        return;
    }

    var $savedNode = $slick.clone();

    var slickOrNot = function() {
        var $windowWidth = $(window).width();
        if ($windowWidth > 500) {
            if (!$slick.hasClass("slick-initialized")) {
                $slick.slick(slickSettings);
            }
        } else {
            if ($slick.hasClass("slick-initialized")) {
                $slick.slick('unslick');
                $slick.after($savedNode);
                $slick.remove();
                $slick = $savedNode;
                $savedNode = $slick.clone();
            }
        }
    };

    slickOrNot();
    $(window).resize(slickOrNot);
})();
```

**Comment by kenwheeler** [comment] 2015-09-07 13:06
Closing, but an upcoming release should have re-enable functionality.

**Closed by kenwheeler** 2015-09-07 13:06 UTC

**Comment by jackbarham** [comment] 2015-09-07 13:21
Sounds good - Drop a message on this thread when you do. Here is an example of the above code in use: http://www.cradle.agency
