### ISSUE TITLE
Bug: variableWidth + Infinite 

### ISSUE THREAD

**Issue by castledoor** [kenwheeler/slick#1949] opened 2015-12-07 14:55 UTC
when these two options are used,along with slideToScroll,  infinite does not work in the 'prev' direction.  It gets to the end of the slides and then advances forward to get back to the first slide, instead of wrapping.  Have not been able to find a workaround fix for this. not ideal behavior 

http://jsfiddle.net/u68o5tmw/1/

**Comment by mcashley** [comment] 2016-01-15 16:22
Closing and marking as duplicate of:
https://github.com/kenwheeler/slick/issues/1207

Please watch that issue for updates

**Closed by mcashley** 2016-01-15 16:22 UTC
Labels: Invalid: Duplicate
