### ISSUE TITLE
Don't work navigation with 2 rows preview

### ISSUE THREAD

**Issue by PalachNik** [kenwheeler/slick#2570] opened 2016-10-17 07:05 UTC
Good day for all!
Need some help.
Have a slick-gallery with 2rows preview. Second row previews dont work correct asNavFor. 
After clicking on the 2nd row previews displays only the 1st row image.
Use 
//              slidesToShow: 3,
//              slidesPerRow: 3,
//                rows: 2,
dont fix promblem.
NavArrows and NavDots not need.

=================================================================

```
<div class="slider-forA">
            <div>
              <img src="img/slider2/IMG_0256.JPG" style="width:100%; height:100%" alt="Alt 1" />
           </div>
            <div>
              <img src="img/slider2/IMG_0258.JPG" style="width:100%; height:100%" alt="Alt 1" />
           </div>
            <div>
              <img src="img/slider2/IMG_0264.JPG" style="width:100%; height:100%" alt="Alt 1" />
           </div>
            <div>
              <img src="img/slider2/IMG_9270.JPG" style="width:100%; height:100%" alt="Alt 1" />
            </div>
            <div>
              <img src="img/slider2/IMG_9279.JPG" style="width:100%; height:100%" alt="Alt 1" />
           </div>
            <div>
              <img src="img/slider2/IMG_9279.JPG" style="width:100%; height:100%" alt="Alt 1" />
            </div>
          </div>
          <div class="slider-navA">
                <div class="FlatPlanSlickA">
                  <img src="img/slider2/IMG_0256.JPG" style="width: 100%" alt="Alt 1" />
               </div>
                <div class="FlatPlanSlickA">
                  <img src="img/slider2/IMG_0258.JPG"  style="width: 100%" alt="Alt 1" />
               </div>
                <div class="FlatPlanSlickA">
                  <img src="img/slider2/IMG_0264.JPG"  style="width: 100%" alt="Alt 1" />
               </div>
                <div class="FlatPlanSlickA">
                  <img src="img/slider2/IMG_9270.JPG" style="width: 100%" alt="Alt 1" />
               </div>
                <div class="FlatPlanSlickA">
                  <img src="img/slider2/IMG_9279.JPG"  style="width: 100%" alt="Alt 1" />
               </div>
                <div class="FlatPlanSlickA">
                  <img src="img/slider2/IMG_9292.JPG"  style="width: 100%" alt="Alt 1" />
               </div>
            </div>
         
          <script>
            $(document).ready(function(){
              $('.slider-forA').slick({
                asNavFor: '.slider-navA',
                slidesToShow: 1,
                slidesToScroll: 1,
                arrows: false,
                fade: true,
              });
              $('.slider-navA').slick({
                slidesToShow: 6,  
//              slidesToShow: 3,
//              slidesPerRow: 3,
//                rows: 2,
                slidesToScroll: 1,
                asNavFor: '.slider-forA',
                dots: false,
                centerMode: false,
                focusOnSelect: true,
                prevArrow: "<button type='button' class='slick-prev'><span class='glyphicon glyphicon-chevron-left' aria-hidden='true'></span></button>",
                nextArrow: "<button type='button' class='slick-next'><span class='glyphicon glyphicon-chevron-right' aria-hidden='true'></span></button>"
              });
              $('.slider-forA').on('beforeChange', function(event, slick, currentSlide, nextSlide){
                console.log(arguments);
              });
            });
          </script>
```

====================================================================

====================================================================

#### More Details

![image](https://cloud.githubusercontent.com/assets/6587445/19428045/5b52fa3a-9450-11e6-9ca0-d1e1059ee74a.png)

- Which jQuery/Slick version are you using? 
Slick Version: 1.5.9
1.11.3 jQuery

=====================

Please help fix problem!
With best regards!

**Comment by PalachNik** [comment] 2016-10-17 07:38
1row preview
![image](https://cloud.githubusercontent.com/assets/6587445/19428758/90aad8c0-9454-11e6-9cc3-ee7691fe503d.png)

**Comment by PalachNik** [comment] 2016-10-17 07:43
2 rows preview
Any previews dont work as navigation. (((

![image](https://cloud.githubusercontent.com/assets/6587445/19429071/5f43ff08-9456-11e6-91a4-e6c1599436a1.png)


```
<script>
            $(document).ready(function(){
              $('.slider-forA').slick({
                asNavFor: '.slider-navA',
                slidesToShow: 1,
                slidesToScroll: 1,

                arrows: false,
                fade: true,
              });
              $('.slider-navA').slick({
//                slidesToShow: 3,
                slidesPerRow: 3,
                rows: 2,
                slidesToScroll: 1,
                asNavFor: '.slider-forA',
                dots: false,
                centerMode: false,
                focusOnSelect: true,
                prevArrow: "<button type='button' class='slick-prev'><span class='glyphicon glyphicon-chevron-left' aria-hidden='true'></span></button>",
                nextArrow: "<button type='button' class='slick-next'><span class='glyphicon glyphicon-chevron-right' aria-hidden='true'></span></button>"
              });

          </script>
```

**Comment by leggomuhgreggo** [comment] 2016-10-18 23:37
Hey, @PalachNik, can you make a reduced test case? You can fork the fiddle in the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). Reduced test cases are pretty crucial, because so often environmental errors are the cause of issues, and the process of recreating them in a reduced environment often reveals the issue. Also it's good form, because, in the event there is a bug with the slider, it makes debugging easier for people on whom you call for assistance. Best of luck and thanks!

Closing pending test case

**Closed by leggomuhgreggo** 2016-10-18 23:37 UTC

**Comment by maurop123** [comment] 2016-10-20 03:26
Here's a [fiddle](http://jsfiddle.net/fmo50w7n/674/) that shows the issue.
