### ISSUE TITLE
centerMode + swipeToSlide failing

### ISSUE THREAD

**Issue by nithiz** [kenwheeler/slick#819] opened 2014-11-21 09:53 UTC
Whenever you have centerMode and swipeToSlide enabled at the same time swiping backwards (swiping to the right) works fine. However, when you swipe to the left (forwards) it will totally ignore the swipeToSlide option and still slide one at the time.

**Comment by RadGH** [comment] 2015-01-02 19:03
I'm also experiencing this issue while also using the sync option. The problem is that when you have centerMode enabled, the calculation for which slide you have scrolled to is still based on the left of the container, instead of the center. This means if you want to swipe to the next slide, you have to slide all the way to the left so that the current slide is at the edge of the container.

Here is a video of the issue from my dev site:
https://gfycat.com/TameIdealisticJumpingbean

Here is a fiddle with some bullet-points clarifying what the problem is and my best guess as to why they are happening:
http://jsfiddle.net/g1a5tq9o/1/

**Comment by vitekvil** [comment] 2015-01-10 11:27
in version 1.3.11 all is ok so try it, Ken respect for your code. You can serach what was changed from that version

**Comment by vitekvil** [comment] 2015-01-17 06:48
really need fix of this problem in newer versions because old one has more difficult bugs

**Comment by sroddy** [comment] 2015-01-24 09:14
i can confirm this is the commit that broke the previously working behavior:
https://github.com/kenwheeler/slick/commit/0d43e7e4c3679da9dff8d7f7ef0d35f23c55dfd2

reverting only this commit on latest branch makes everything else work as expected

**Comment by kenwheeler** [comment] 2015-01-25 03:33
Fixed on  dev

**Closed by kenwheeler** 2015-01-25 03:33 UTC
Labels: Confirmed Bug
