### ISSUE TITLE
Adding "fade: true" breaks lazy loading

### ISSUE THREAD

**Issue by johanngonzalez** [kenwheeler/slick#2153] opened 2016-02-23 15:08 UTC
While constructing a carousel using lazyLoad I've noticed that if I had the "fade: True" option, all images will load right away instead of using lazyLoad. 

Here's the code I used in order to reproduce the problem:

$('.single-item').slick({
  dots: true,
  infinite: true,
  speed: 500,
  lazyLoad: 'ondemand',
  slidesToShow: 1,
  cssEase: 'linear',
  fade: true
  
});

**Comment by leggomuhgreggo** [comment] 2016-02-23 18:14
Hey I think this is a duplicate of [this issue](https://github.com/kenwheeler/slick/issues/1481). Im going to close it to avoid the clutter, but if you think it's different we can look at reopening. Also, check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), for bugs it's pretty crucial to have a reduced test case in a fiddle or something. Thanks!

**Closed by leggomuhgreggo** 2016-02-23 18:14 UTC
