### ISSUE TITLE
Center mode issue when slideCount == slidesToShow

### ISSUE THREAD

**Issue by stephanemartinw** [kenwheeler/slick#2472] opened 2016-08-16 09:47 UTC
With center mode on, when the slides count equals the total numbers of slides (3 for me), center classes are incorrectly added : 'slick-center' is added to the first and the last item, not to the second one.

My slick is intialized like this : 

  $('.carousel').slick({
          centerMode: true,
          centerPadding: '0px',
          slidesToScroll: 1,
          slidesToShow: 3,
          responsive: [
            {
              breakpoint: 768,
              settings: {
                arrows: false,
                centerMode: true,
                centerPadding: '0px',
                slidesToShow: 1,
                slidesToScroll: 1
              }
            }
          ]
        });

**Comment by leggomuhgreggo** [comment] 2016-08-16 20:40
@stephanemartinw Hey this is a duplicate of a known issue. Thanks for the report.

**Closed by leggomuhgreggo** 2016-08-16 20:40 UTC
