### ISSUE TITLE
It adds "slick-current" class to more than one slide

### ISSUE THREAD

**Issue by pruthvi-k** [kenwheeler/slick#2115] opened 2016-02-11 12:07 UTC
When "slidesToShow" is equal to total slide it gives problem

Check out [Jsfiddle](http://jsfiddle.net/1wyegw6L/2/)

`.slick({
            slidesToScroll: 1,
            centerMode: true,
            centerPadding: '60px',
            slidesToShow: 3,
            focusOnSelect: true,
            arrows: false,
            responsive: [
                {
                    breakpoint: 769,
                    settings: {
                        arrows: false,
                        centerMode: false,
                        centerPadding: '40px',
                        slidesToShow: 1,
                        dots: true
                    }
                }
            ]
        });`

Here number of slides is same as slidesToShow, ideally it should add class "slick-center" only to middle slide but it is adding that class to first and last one,also it is not moving to center. I found it is causing problem at line 2150 in slick.js.

Issue is when there are only 3 slides

**Comment by leggomuhgreggo** [comment] 2016-02-11 23:19
Hey @pruthvi-k, I think this relates to several open issues having to do with slideCount <= slidesToShow, centerMode, and asNavFor. There are a bunch of them, with various use cases, but #659, #1027, and #1189 are related. Since it's more or less a duplicate of those issues, I'm going to close it, but thank you for taking the time to report it--I think it's a good topic to bump.

**Closed by leggomuhgreggo** 2016-02-11 23:19 UTC
Labels: Invalid: Duplicate
