### ISSUE TITLE
Reinitialize after ajax page load

### ISSUE THREAD

**Issue by padjodev** [kenwheeler/slick#2204] opened 2016-03-17 17:27 UTC
Basically Ive built an ajax driven site. When you click a nav link its rel value will load that page and grab its content using jquerys contents function as follows

        namespace.ajax.done(function(msg) {
           var lll = $(msg).find("#containment");      
           var dd = lll.contents();
                $("#containment").html(dd);
        }),

I am using modernizer to load page specific script for each page and in the script for the homepage i have slick initialized as so 

$('.social-wall-masonry').slick({
          dots: false,
          infinite: true,
          slidesToShow: 5,
          autoplay: true,
        });

this works fine when you manually refresh but when the page contents are pulled in it cant find the element '.social-wall-masonry' and initialize the slick for that page.... is there any kind of way to get the dynamic js file to execute the slick slider everytime or to find that dynamic element ?

**Comment by leggomuhgreggo** [comment] 2016-03-17 17:45
Hey @padjodev I think you'll want to reinit the slick on the ajax callback or remove/add slides.

I'm going to close this because it's a support request and not a bug

Hope that helps

**Closed by leggomuhgreggo** 2016-03-17 17:45 UTC
