### ISSUE TITLE
set max loop count

### ISSUE THREAD

**Issue by SpacemanPete** [kenwheeler/slick#2033] opened 2016-01-15 21:18 UTC
Apologies if this has been asked before I browsed through issues and google around but could not find a similar question. 

Given a slide list of 4 items autoplaying one slide at a time, is there a way to set a max loop counter so that it will loop through the list 4 times or 16 slides in total?

I don't want it to loop infinitely but I also don't want to loop through the list only once...

**Comment by kenwheeler** [comment] 2016-01-15 22:05
I'm sorry, and I don't mean to single you out. But I'm going to. This isn't a support forum, this is where we report bugs in projects. This is not a bug. It is a support request.

This project does indeed have bugs. Bugs that aren't being fixed because I can't find them amid a sea of support requests.

Instead of telling you to go away and close this issue, I'm going to show you how to not do this anymore, to anyone. Because you asked nicely and I appreciate that.

So I think we can both agree from the start, that this is not a bug. 

You have my library, which has a documented API, and you have jQuery, which also has a documented API. Lets put the pieces together.

You have a list of 4 items, playing one slide at a time. 

You want to count the number of full iterations, and stop after 4 iterations have completed.

Lets begin:

We need to find out when a full iteration has occured. A great way to do that, is to listen for the slides changing. How do we do that?

Turns out, we can listen for events: https://github.com/kenwheeler/slick#events

Let's set up an event listener using the `afterChange` event.

```javascript
function handleEvent(e, slick, currentSlide) {

}

$('.slider').on('afterChange', handleEvent);
```

Notice we have three arguments. The event, the slick instance, and the current slide. Using them, we can find out what slide we are on.

The next logical step is to use this event to find out how many times we have reached the last slide.

Let's set up a variable to store that in:

```javascript
var iterations = 0;
```

Now we can increment that variable when we hit the last slide:

```javascript
var iterations = 0;

function handleEvent(e, slick, currentSlide) {
    if (currentSlide === slick.slideCount - 1) {
        iterations++;
    }
}

$('.slider').on('afterChange', handleEvent);
```

Now we can use the `setOption` method to turn autoplay off, and remove our event listener:

```javascript

var iterations = 0;

function handleEvent(e, slick, currentSlide) {
  if (currentSlide === slick.slideCount - 1) {
      iterations++;
      if (iterations === 4) {
        $('.slider').slick('setOption', 'autoplay', false);
        $('.slider').off('afterChange', handleEvent);
      }
  }
}

var iterationEvent = $('.slider').on('afterChange', handleEvent);
```

And there you have it:

http://jsfiddle.net/2eLky4vo/1/

Using the browser, Slick & jQuery APIs we were able to implement this in a trivial amount of code. At no point did a bug surface in the library. 

You may be asking yourself, why would Ken take the time to write this out. Because you aren't going to do this to this repo or any repo ever again. Moving forward, you are going to become a programming god, by deconstructing a problem, looking at your available tools (API) and figuring out how to achieve your requirements using those tools. 

And if during the course of that process, you do find a bug, please, by all means, send it my way with a jsfiddle demonstrating the bug, and I'll happily take a look.

**Closed** 2016-01-15 22:08 UTC

**Comment by SpacemanPete** [comment] 2016-01-23 19:51
Hi Ken, 

Thank you for the kind response and I don't mind you singling me out. I'm a woodworker-turned-programmer with less than a year of professional programming under my belt so I realize that at times I am inexperienced at deconstructing a problem and unsure of the protocols for asking support from various places around the web, so thanks for educating me without biting my head off. Advice like this is as valuable as actual coding skills in the tech biz.

I will keep it in mind to limit posts in the 'Issues" forums to bug reports. 

And many thanks for walking through deconstructing the problem in so much detail! Examples like this are so informative in helping me learn the thought process behind approaching and solving a programming challenge.
It was kind of you to take the time to do it and I'll be sure to pay it forward when I can!

Best,
-Piotr

**Comment by kenwheeler** [comment] 2016-01-24 01:56
Oh man I wish I could woodwork. I tried to make a pegboard and blew it. Any time you want to talk about a programming problem hit me at my email on my profile.

**Comment by simeydotme** [comment] 2016-01-24 06:53
:+1: (+1) 
Great that this hit on a legitimate person looking to sort their own problems out with a little help. Thats invaluable and I hope you keep up the quest for knowledge, Piotr! :grin: 

And like Ken; if you need any help with something and I have experience in, go ahead and hit me on twitter/email :smiley:. You'll find the community thrives on -- and cares about -- giving people the tools to fix their own problems, but there's many people who are just looking to submit the least amount of effort as possible and expect others to solve their problems. It's a shame.

The best way you can get results is by posting your problem on Stackoverflow (it can be harsh there, but there's rules for a reason -- just remember to read them) and then send one of the collaborators a message in "Gitter" with a link to that issue. -- that way if we don't have time to look at it right away, at least the whole of Stackoverflow can help! :) (and eventually you can give back to the community that helped you)

I've literally seen people tell Ken he has to fix something; and given him a deadline; because it doesn't work how they expect. Hilarious, and disheartening.
