### ISSUE TITLE
Destroy/init on a carousel breaks it since 1.6.0

### ISSUE THREAD

**Issue by terzag** [kenwheeler/slick#2324] opened 2016-05-17 17:21 UTC
Here is the context: on a web page, I have two carousels which I have to toggle through Javascript (only one carousel displayed at the same time).
So, basically, I have both in the page and when it loads I hide the second carousel (css: display = none). When clicking on some links to toggle them, I hide one carousel and show the other one.

There's a small issue with this. My carousels display images and I load them through lazy-loading (progressive). It turns out that showing the first hidden carousel doesn't load its images. I found a fix for this: setting a destroy and init events on the carousels fixes the issue (I assume it forces reloading the images).

I don't know if it's the right way to do this, if it's a dirty hack, if someone has a better solution for toggling the display of two carousels... Anyway, it worked fine with slick 1.5.9 but doesn't anymore with 1.6.0. With that version, if I load the page, the visible carousel works fine, but as soon as I toggle one I can't display more than two slides, after this the navigation becomes unresponsive on both carousels.

I've put a JSFiddle showing the issue there: http://jsfiddle.net/ngjrjcfz/3/ (I hope I share it right, that's the first time I use it).

You can check the following:
1) use the first carousel displayed as much as you want, all sliders and navigation work
2) click on "show carousel 2"
3) click on the right arrow or a dot, you'll notice that you can only do it once, then the navigation is broken
4) click on "show carousel 1": its navigation is now broken too

Have tested the behaviour on Google Chrome and Firefox on Linux.

**Comment by leggomuhgreggo** [comment] 2016-05-18 05:20
Hmm can you show it working in 1.5.9?

Here are some easy workarounds though:
http://jsfiddle.net/u2nLpwys/
http://jsfiddle.net/n57b3asL/

**Comment by terzag** [comment] 2016-05-18 08:02
Well, it is currently working on a website I'm working on. It's not yet public, though, I'll try to setup a test one.

**Comment by terzag** [comment] 2016-05-19 07:13
I have small issues on my server so I've put the test case with Slick 1.5.9 on a more stable place: http://www.terzag.info/test-dual-carousel/

**Comment by leggomuhgreggo** [comment] 2016-05-19 16:38
Ahhh for the 1.5.9 case I just meant could you fork your initial fiddle and swap the library to the 1.5.9 edition. It's important when testing to reduce variables; the demo you made on your side, while appreciated, has a lot of variables and isn't as easy to debug. Anyway I went ahead and did it and confirmed: [Here](http://jsfiddle.net/bbs953hp/).

options solution: You can retrieve the option set from the slick object before you unslick, or you could set is as a js variable using PHP

visibility solution: True that visibility preserves document flow, but you can get around that by making the second one absolutely positioned to a relatively positioned container that holds both.

I'll look into what changed between the versions in a bit.

**Comment by terzag** [comment] 2016-05-19 17:06
Oh, ok, my bad. I'm not sure to know how to swap the library version on JSFiddle (this website is pretty mysterious to me). Not sure either of what you did: the JSFiddle you're linking is the same (Slick 1.6.0) as the one I posted, right?

How would I retrieve the options for a specific Slick object? I'm not really a JS developer. Do I simply put the existing object in a var or something like that?

**Comment by leggomuhgreggo** [comment] 2016-05-19 20:03
>I'm not sure to know how to swap the library version on JSFiddle

It is a little ticky, but it's pretty crucial if you're gonna be githubbing. In JSFiddle theres a sidebar on the left with an "external resources" accordion, that includes files dependencies like the slick styles and js. I replaced the slick.js with the 1.5.9 version. I think you can get older versions of the JS from the various CDNs that've been hosting, but you can also go to the old release in github and find the url for the raw js. Now you'd think you'd be able to use that but github doesnt provide the necessary server headers to include it straight from the URL, so you have to throw it up on rawgit.com. 

>How would I retrieve the options for a specific Slick object? 

Ye, it's been awhile since I've worked in PHP but it should be something along the lines of: 
```
<script>
var slickOptions = $phpJonx;
</script>
```
Just store the php values in a global js var on compile, and the client can use it then.

**Comment by terzag** [comment] 2016-05-19 20:36
Oh, I saw the column on the left but I kept clicking on the "+" icon to add one and it did nothing; I thought I had to find the option elsewhere. Took me a while to figure that the "Javascript/CSS URI" placeholder is an input field...

Ok, so I now have the two versions (for reference):
- with Slick 1.5.9 (working) : http://jsfiddle.net/ngjrjcfz/5/
- with Slick 1.6.0 (not working) : http://jsfiddle.net/ngjrjcfz/3/

**Comment by leggomuhgreggo** [comment] 2016-05-19 20:42
Cool thanks. Since there are workarounds, I'm going to consider this non-critical, but I will try to look into it later.

**Comment by terzag** [comment] 2016-05-19 20:45
Thanks. Currently, I'll stick with v 1.5.9 as it works the way I need it to. :)

**Comment by mazzaker** [comment] 2016-05-27 09:59
[Fiddle](http://jsfiddle.net/ngjrjcfz/7/)

Seems to work by passing the settings on init.

**Comment by terzag** [comment] 2016-05-27 10:10
Yeah. But there are two things that annoy me:

1) As said above, I'd like to be able to avoid this, as I don't have an easy way to get the initial settings (they're set through a WP plugin and the special case of toggling between two carousels is on a specific page of a website that uses that plugin).

2) With version 1.5.9 and the destroy/init methods I'm using, the carousels keep their slide position when toggled (e.g. go to slide 3 on carousel no. 1, toggle it with no. 2, go to slide 2, toggle back to no. 1, it's still on the third slide). With the example you've put on JSFiddle, the current slide of each carousel resets when toggled. It's really important to me to keep the previous behaviour.

**Comment by mazzaker** [comment] 2016-05-27 10:20
Ok but I do not see any issue when set the slider to display none in the current version...

Pasted the images from your example to see any issues regarding the lazyLoad
[Fiddle](http://jsfiddle.net/ngjrjcfz/9/)

**Comment by terzag** [comment] 2016-05-27 10:27
That's weird: it indeed works with that last fiddle which doesn't use the destroy/init tweak that I had to setup on my website.

I'll check again: maybe there was a bug in lazy loading with Slick 1.5.9 that has been fixed in 1.6.0?

I'll look into this more thoroughly later.

**Comment by terzag** [comment] 2016-05-27 11:31
Ok, I've updated Slick to 1.6.0 and removed the destroy/init stuff and it seems to work, so it looks like I was trying to turn around a bug that had been fixed... (?)

I have another problem, though, which is specific to the way I setup Slick with my plugin: it applies Slick to all the carousels on the page when it's loaded (triggered by window.onload) but my code for toggling carousels and hiding one is at the bottom of the specific page that use it. TL;DR: I init the carousels after the second one in the page is hidden. Consequence: it isn't initialized properly.

Example simulated there: http://jsfiddle.net/ngjrjcfz/10/
If you show carousel 2, you'll see that it displays the last slide but considers it as the first one. I.e. if you click on the right arrow, it will go to slide 2 as expected but without the sliding effect.

Any advice on the best way to handle this?

**Comment by simeydotme** [comment] 2016-05-31 18:28
I think your "bug" is not an issue anymore, and you're now asking for support so I'll close this :)

**Closed by simeydotme** 2016-05-31 18:28 UTC
Labels: Bug: Investigating

**Comment by terzag** [comment] 2016-05-31 20:24
Yeah, it seems to be fixed on my side.

It might be worth investigating, though, as something that worked in 1.5.9 appears really broken in 1.6.0, even if it shows only for a very specific case.

**Comment by mazzaker** [comment] 2016-06-01 09:49
I think it is correct in the current version destroying the slider should not keep the settings for the slider. Destroyed element = never existed element!

**Comment by terzag** [comment] 2016-06-01 09:52
But then, shouldn't the init that follows the destroy reset the carousel view? In my original example, when toggling the carousel, it displays the previous slide it was on and then all breaks apart after changing the slide once.
