### ISSUE TITLE
slidesToShow in vertical mode

### ISSUE THREAD

**Issue by alarstyle** [kenwheeler/slick#1779] opened 2015-09-29 02:56 UTC
`slidesToShow` option is ignored in vertical mode.

**Comment by mparker11** [comment] 2015-11-21 00:19
Having the same issue. I'm using the slider with Foundation's tab system so once a tab is clicked, if the div is empty, I load info through an ajax call. I'm limiting my results to 15 elements and have my "slidesToShow" option set at 5. However, 7 1/2 items show on first load. The odd part is, when I click the arrows to scroll, the slider adjusts itself and it works as expected.

Here's my code after my ajax load is complete:

```
$(.tabs-panel.is-active').html(data.html);
$('.tabs-panel.is-active').slick({
	arrows: false,
	dots: true,
	slidesToShow: 5,
	slidesToScroll: 5,
	vertical: true,
	verticalSwiping: true
});
```

Any ideas?

**Comment by pptp** [comment] 2015-11-26 05:22
I also subscribe to the issue
The issue can be fixed by changing the method "Slick.prototype.getSlideCount" and adding a checking for vertical mode.

**Comment by pptp** [comment] 2015-11-26 11:03
My solution is:
```javascript
Slick.prototype.getSlideCount = function() {
        var _ = this,
            slidesTraversed, swipedSlide, centerOffset,
            isSwiped;
        centerOffset = _.options.centerMode === true ? _.slideWidth * Math.floor(_.options.slidesToShow / 2) : 0;
        if (!!_.options.verticalSwiping) {
            isSwiped = function(slide) {
                return (slide.offsetTop - centerOffset + ($(slide).outerHeight() / 2) > (_.swipeLeft * -1))
            }
        } else {
            isSwiped = function(slide) {
                return (slide.offsetLeft - centerOffset + ($(slide).outerWidth() / 2) > (_.swipeLeft * -1));
            }
        }
        if (_.options.swipeToSlide === true) {
            _.$slideTrack.find('.slick-slide').each(function(index, slide) {
                if (isSwiped(slide)) {
                    swipedSlide = slide;
                    return false;
                }
            });
            slidesTraversed = Math.abs($(swipedSlide).attr('data-slick-index') - _.currentSlide) || 1;
            return slidesTraversed;
        } else {
            return _.options.slidesToScroll;
        }
    };
```

**Comment by Bitneko** [comment] 2015-12-15 12:39
I just tried pptp's solution and it works perfectly

**Comment by mcashley** [comment] 2016-01-16 23:25
I cannot reproduce what the exact problem is. Slides to show and vertical works here: https://jsfiddle.net/1a8ewgef/

Closing. Please add more information and a JSFiddle example to reopen

**Closed by mcashley** 2016-01-16 23:25 UTC

**Comment by pptp** [comment] 2016-01-18 07:39
mcashley, vertical slides are not scrollable in this example

**Comment by pptp** [comment] 2016-01-18 07:40
To reproduce the problem: make the viewport narrow to make slides be vertical and try to scroll them by touch

**Comment by sinnis-dev-trey** [comment] 2018-03-05 09:15
Can confirm this still seems to be an issue? I have 6/7 slides with this code:

```
$('.featured-dealer-reviews').slick({
    arrows:         false,
    slidesToShow:   3,
    vertical:       true,
    verticalSwiping: true
});
```
yet all 6/7 are shown with the last one having the last 30px or so cut off and displayed before the first slide? may be some CSS issues?

(using Bootstrap, Wordpress and FontAwesome libraries)
