### ISSUE TITLE
slick 1.5.6 conflict issue

### ISSUE THREAD

**Issue by wannamax** [kenwheeler/slick#1538] opened 2015-07-16 06:09 UTC
I have tried multi slick slider on this page http://bestmua.vn/2015/brand-index2.html
 Version: 1.5.6
and slick slider got messed up as above link (no problem with previous version 1.4.x) if you use any responsive setting value like:
responsive: [
    {
      breakpoint: xxx,
      settings: {

      }
    }
remove this code and it works. is this a bug? Please advise.

**Comment by meneldil** [comment] 2015-07-16 17:09
Same problem when we set "arrow" to "true".
If we set "false" it works again.
The problem is coming from there.

**Comment by simeydotme** [comment] 2015-07-18 03:43
Sorry guys, this was fixed on thr master branch. Waiting for a release :)

**Closed by simeydotme** 2015-07-18 03:43 UTC
